function Get-DeviceAssignedServerDetails {
    [CmdletBinding(DefaultParameterSetName = 'Limit'
                ,  HelpURI = 'https://developer.apple.com/documentation/applebusinessmanagerapi/get-orgdeviceactivity-information')]
    param (
        [Parameter(Mandatory = $true
                ,  ValueFromPipeline = $true
                ,  ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $DeviceId
        ,
        [Parameter()]
        [ValidateSet('serverName', 'serverType', 'createdDateTime', 'updatedDateTime', 'devices')]
        [string[]]
        $Fields
        ,
        [Parameter()]
        [switch]
        $Raw
    )
    begin {
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): ParameterSet: '$($PSCmdlet.ParameterSetName)'. $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"
    }
    process {
        $QueryString = [System.Web.HttpUtility]::ParseQueryString($null)
        $UriBuilder = [System.UriBuilder]::new($Script:Config.ApiUrl)
        $UriBuilder.Path += "/$([uri]::EscapeDataString('orgDevices'))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString($DeviceId))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString('assignedServer'))"
        if ($PSBoundParameters.ContainsKey('Fields')) { $QueryString.Set('fields[orgDevices]', $Fields -join ',') }
        $UriBuilder.Query = $QueryString.ToString()
        try {
            $Response = Invoke-ApiRequest -Method Get -Uri $UriBuilder.Uri
            if ($Raw) { $Response }
            else { $Response.data }
        }
        catch {
            if (Test-Json -Json $_.ErrorDetails.Message) {
                $ErrorResponse = ($_.ErrorDetails.Message | ConvertFrom-Json -Depth 5).errors[0]
                switch ($ErrorResponse.status) {
                    404 { return $null }
                    Default { throw $ErrorResponse }
                }
            }
            throw $_
        }
    }
    <#
    .SYNOPSIS
    Gets the assigned device management service information for a device.

    .DESCRIPTION
    Gets the assigned device management service (MDM server) information for a specific device in Apple Business Manager. This retrieves details about which management service is assigned to handle the device.

    .PARAMETER DeviceId
    The unique identifier for the device. This parameter is required and accepts input via pipeline by property name.

    .PARAMETER Fields
    Specifies which server attributes to return in the response. If not specified, all fields are returned.
    
    Valid values include: serverName, serverType, createdDateTime, updatedDateTime, devices

    .PARAMETER Raw
    When specified, returns the complete API response object including metadata. Otherwise returns only the server data.

    .OUTPUTS
    System.Object
    When Raw is not specified: Returns PSCustomObject with assigned server information.
    When Raw is specified: Returns the full API response object with metadata.

    .EXAMPLE
    Get-DeviceAssignedServerDetails -DeviceId 'ABC123DEF456'
    Gets the assigned device management service information for a specific device.

    .EXAMPLE
    Get-DeviceAssignedServerDetails -DeviceId 'ABC123DEF456' -Fields serverName, serverType
    Gets specific server details for a device.

    .EXAMPLE
    Get-DeviceAssignedServerDetails -DeviceId 'ABC123DEF456' -Raw
    Gets the assigned server information and returns the complete API response.

    .NOTES
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    https://developer.apple.com/documentation/applebusinessmanagerapi/get-the-assigned-device-management-service-information-for-an-orgdevice
    #>
}