function Invoke-ApiRequest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [Alias('ApiUrl')]
        [uri]
        $Uri
        ,
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [Microsoft.PowerShell.Commands.WebRequestMethod]
        $Method
        ,
        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]
        $Body
        ,
        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]
        $ContentType = 'application/json'
    )
    Write-Debug -Message "$($MyInvocation.MyCommand.Name): $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"

    # Check for the configuration and its keys.
    if (!$Script:Config -or !$Script:Config.Key -or !$Script:Config.KeyId -or 
        !$Script:Config.ClientId -or !$Script:Config.TokenUrl -or !$Script:Config.TimeToLive) {
        throw "Configuration is missing. Please create a configuration using New-ApiConfig or import one using Import-ApiConfig."
    }
    $Attributes = @{
        Key        = $Script:Config.Key
        KeyId      = $Script:Config.KeyId
        ClientId   = $Script:Config.ClientId
        TokenUrl   = $Script:Config.TokenUrl
        TimeToLive = $Script:Config.TimeToLive
    }
    # Check for access token and its validity.
    Write-Debug -Message "$($MyInvocation.MyCommand.Name): $($Script:Api | ConvertTo-Json -Compress)"
    $Global:DebugApi = $Script:Api
    if (!$Script:Api -or !$Script:Api.AccessToken -or !$Script:Api.ExpiresAt -or 
        $Script:Api.ExpiresAt -lt [datetime]::Now.AddSeconds(30)) {
        # Request a new access token.
        $Response = Request-AccessToken @Attributes
        $Script:Api.AccessToken = $Response.access_token
        $Script:Api.ExpiresAt = [datetime]::Now.AddSeconds($Response.expires_in)
    }
    $Headers = @{
        Authorization = "Bearer $($Script:Api.AccessToken)"
    }
    $Attributes = @{
        Headers = $Headers
        Method = $Method
        ContentType = $ContentType
        UseBasicParsing = $true
        Uri = $Uri
    }
    if ($Body) { $Attributes.Body = $Body }
    $Response = Invoke-WebRequest @Attributes
    $Response.Content | ConvertFrom-Json -Depth 10
    <#
    .SYNOPSIS
    Invokes an authenticated API request to the Apple Business Manager API.

    .DESCRIPTION
    Sends an authenticated HTTP request to the Apple Business Manager API. This is an internal helper function used by other cmdlets in the module. It automatically manages access token generation, renewal, and expiration monitoring. The function handles authorization headers and JSON serialization/deserialization transparently.

    .PARAMETER Uri
    The uniform resource identifier (API endpoint URL) to send the request to. Required.

    .PARAMETER Method
    The HTTP method for the request. Valid values include: Get, Post, Put, Patch, Delete, Head, Options, Trace. Required.

    .PARAMETER Body
    The request body content as a JSON string. Optional. If provided, it will be sent with the specified Content-Type header.

    .PARAMETER ContentType
    The content type of the request body. Default is 'application/json'. Optional.

    .OUTPUTS
    System.Object
    Returns the parsed JSON response from the API as a PowerShell object.

    .EXAMPLE
    $Response = Invoke-ApiRequest -Method Get -Uri 'https://api-business.apple.com/v1/orgDevices'
    Sends an authenticated GET request to retrieve organization devices.

    .EXAMPLE
    $Body = @{ data = @{ type = 'orgDevices'; id = 'device123' } } | ConvertTo-Json
    $Response = Invoke-ApiRequest -Method Post -Uri 'https://api-business.apple.com/v1/orgDeviceActivities' -Body $Body
    Sends an authenticated POST request with a JSON body.

    .NOTES
    This is an internal helper function used by other module cmdlets.
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    The function automatically:
    - Validates configuration is loaded (Key, KeyId, ClientId, TokenUrl, TimeToLive)
    - Manages access token generation and renewal
    - Adds Bearer token authorization header
    - Parses JSON responses with depth of 10

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    New-ApiConfig

    .LINK
    Import-ApiConfig
    #>
}