function Set-DeviceServer {
    [CmdletBinding(DefaultParameterSetName = 'Assign'
                ,  HelpURI = 'https://developer.apple.com/documentation/applebusinessmanagerapi/create-an-orgdeviceactivity')]
    param (
        [Parameter(ParameterSetName = 'Assign'
                ,  Mandatory = $true)]
        [switch]
        $Assign
        ,
        [Parameter(ParameterSetName = 'Unassign'
                ,  Mandatory = $true)]
        [switch]
        $Unassign
        ,
        [Parameter(Mandatory = $true)]
        [string]
        $ServerId
        ,
        [Parameter(Mandatory = $true
                ,  ValueFromPipeline = $true
                ,  ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string[]]
        $DeviceId
    )
    begin {
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): ParameterSet: '$($PSCmdlet.ParameterSetName)'. $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"
        $Activity = if ($Unassign) { 'UNASSIGN_DEVICES' } else { 'ASSIGN_DEVICES' }
        $Data = @{
            data = @{
                type = 'orgDeviceActivities'
                attributes = @{
                    activityType = $Activity
                }
                relationships = @{
                    mdmServer = @{
                        data = @{
                            type = 'mdmServers'
                            id = $ServerId
                        }
                    }
                    devices = @{}
                }
            }
        }
    }
    process {
        $UriBuilder = [System.UriBuilder]::new($Script:Config.ApiUrl)
        $UriBuilder.Path += "/$([uri]::EscapeDataString('orgDeviceActivities'))"
        $Data.data.relationships.devices.data = @()
        foreach ($Id in $DeviceId) {
            $Data.data.relationships.devices.data += @{
                type = 'orgDevices'
                id = $Id
            }
        }
        $Payload = $Data | ConvertTo-Json -Compress -Depth 5
        $Request = @{
            Uri    = $UriBuilder.Uri
            Method = 'POST'
            Body   = $Payload
        }
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): Invoke-ApiRequest $($Request | ConvertTo-Json -Compress -Depth 10 -WarningAction SilentlyContinue)"
        try {
            Invoke-ApiRequest -Method Post -Uri $UriBuilder.Uri -Body $Payload
        }
        catch {
            throw $_
        }
    }
    <#
    .SYNOPSIS
    Assigns or unassigns devices to a device management service in Apple Business Manager.

    .DESCRIPTION
    Creates an organization device activity to assign or unassign one or more devices to a device management service (MDM server) in Apple Business Manager. The operation is performed by creating an orgDeviceActivity record with the specified action type.

    .PARAMETER Assign
    When specified, assigns the devices to the specified device management service. This parameter is mutually exclusive with Unassign and one of them must be provided.

    .PARAMETER Unassign
    When specified, unassigns the devices from the specified device management service. This parameter is mutually exclusive with Assign and one of them must be provided.

    .PARAMETER ServerId
    The unique identifier for the device management service (MDM server) that devices will be assigned to or unassigned from. This parameter is required.

    .PARAMETER DeviceId
    One or more device identifiers to assign or unassign. Accepts an array of device IDs and supports pipeline input by property name. All specified devices will be included in a single API request.

    .OUTPUTS
    System.Object
    Returns a PSCustomObject containing the organization device activity information created by the API.

    .EXAMPLE
    Set-DeviceServer -Assign -ServerId 'server123' -DeviceId 'device001', 'device002'
    Assigns two devices to the specified device management service.

    .EXAMPLE
    'device001', 'device002' | Set-DeviceServer -Assign -ServerId 'server123'
    Assigns devices piped to the function to the specified device management service.

    .EXAMPLE
    Set-DeviceServer -Unassign -ServerId 'server123' -DeviceId 'device001'
    Unassigns a device from the specified device management service.

    .EXAMPLE
    Get-Device -All | Set-DeviceServer -Assign -ServerId 'server123'
    Assigns all devices retrieved from Get-Device to the specified device management service.

    .NOTES
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    https://developer.apple.com/documentation/applebusinessmanagerapi/create-an-orgdeviceactivity
    #>
}