function Get-DeviceAssignedServerId {
    [CmdletBinding(HelpUri = 'https://developer.apple.com/documentation/applebusinessmanagerapi/get-device-management-services')]
    param (
        [Parameter(Mandatory = $true
                ,  ValueFromPipeline = $true
                ,  ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $DeviceId
        ,
        [Parameter()]
        [switch]
        $Raw
    )
    begin {
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"
    }
    process {
        $UriBuilder = [System.UriBuilder]::new($Script:Config.ApiUrl)
        $UriBuilder.Path += "/$([uri]::EscapeDataString('orgDevices'))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString($DeviceId))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString('relationships'))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString('assignedServer'))"
        try {
            $Response = Invoke-ApiRequest -Method Get -Uri $UriBuilder.Uri
            if ($Raw) { $Response }
            else { $Response.data }
        }
        catch {
            if (Test-Json -Json $_.ErrorDetails.Message) {
                $ErrorResponse = ($_.ErrorDetails.Message | ConvertFrom-Json -Depth 5).errors[0]
                switch ($ErrorResponse.status) {
                    404 { return $null }
                    Default { throw $ErrorResponse }
                }
            }
            throw $_
        }
    }
    <#
    .SYNOPSIS
    Gets the assigned device management service ID for a device.

    .DESCRIPTION
    Gets the assigned device management service ID information for a specific device in Apple Business Manager. This endpoint returns only the relationship information including the object type and the assigned MDM server ID, without additional server details.

    Note: This function uses the /relationships/assignedServer endpoint, which returns minimal information (type and ID only). For more detailed server information, use Get-DeviceAssignedServerDetails.

    .PARAMETER DeviceId
    The unique identifier for the device. This parameter is required and accepts input via pipeline by property name.

    .PARAMETER Raw
    When specified, returns the complete API response object including metadata. Otherwise returns only the relationship data.

    .OUTPUTS
    System.Object
    When Raw is not specified: Returns PSCustomObject with assigned server ID relationship information.
    When Raw is specified: Returns the full API response object with metadata.

    .EXAMPLE
    Get-DeviceAssignedServerId -DeviceId 'ABC123DEF456'
    Gets the assigned device management service ID for a specific device.

    .EXAMPLE
    Get-DeviceAssignedServerId -DeviceId 'ABC123DEF456' -Raw
    Gets the assigned server ID information and returns the complete API response.

    .NOTES
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    https://developer.apple.com/documentation/applebusinessmanagerapi/get-the-assigned-device-management-service-id-for-an-orgdevice
    #>
}