function Get-DeviceAppleCare {
    [CmdletBinding(DefaultParameterSetName = 'Limit'
                ,  HelpURI = 'https://developer.apple.com/documentation/applebusinessmanagerapi/get-applecare-coverage-information-for-an-orgdevice')]
    param (
        [Parameter(Mandatory = $true
                ,  ValueFromPipeline = $true
                ,  ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $DeviceId
        ,
        [Parameter()]
        [ValidateSet('status', 'paymentType', 'description', 'agreementNumber'
                    ,'startDateTime', 'endDateTime', 'isRenewable', 'isCanceled'
                    ,'contractCancelDateTime')]
        [string[]]
        $Fields
        ,
        [Parameter(ParameterSetName = 'Limit')]
        [ValidateRange(1, 1000)]
        [int]
        $Limit
        ,
        [Parameter(ParameterSetName = 'All')]
        [Switch]
        $All
        ,
        [Parameter()]
        [switch]
        $Raw
    )
    begin {
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): ParameterSet: '$($PSCmdlet.ParameterSetName)'. $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"
    }
    process {
        $QueryString = [System.Web.HttpUtility]::ParseQueryString($null)
        $UriBuilder = [System.UriBuilder]::new($Script:Config.ApiUrl)
        $UriBuilder.Path += "/$([uri]::EscapeDataString('orgDevices'))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString($DeviceId))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString('appleCareCoverage'))"
        if ($PSBoundParameters.ContainsKey('Limit')) { $QueryString.Set('limit', $Limit) }
        if ($PSCmdlet.ParameterSetName -eq 'All') { $QueryString.Set('limit', 1000) }
        if ($PSBoundParameters.ContainsKey('Fields')) { $QueryString.Set('fields[orgDevices]', $Fields -join ',') }
        $UriBuilder.Query = $QueryString.ToString()
        $Uri = $UriBuilder.Uri
        do {
            $Response = Invoke-ApiRequest -Method Get -Uri $Uri
            if ($PSCmdlet.ParameterSetName -eq 'Limit' -and !$All) {
                if ($Raw) { return $Response }
                else { return $Response.data }
            }
            $Uri = $Response.links.next
            if ($Raw) { $Response }
            else { $Response.data }
        } while ($Uri)
    }
    <#
    .SYNOPSIS
    Gets AppleCare coverage information for a device in Apple Business Manager.

    .DESCRIPTION
    Gets a list of AppleCare Coverage resources for a specific device in an Apple Business Manager organization. The function supports pagination and field filtering to retrieve detailed coverage information.

    .PARAMETER DeviceId
    The unique identifier for the device. This is typically the device's serial number. This parameter is required and accepts input via pipeline by property name.

    .PARAMETER Fields
    Specifies which AppleCare coverage attributes to return in the response. If not specified, all fields are returned.
    
    Valid values include: status, paymentType, description, agreementNumber, startDateTime, endDateTime, isRenewable, isCanceled, contractCancelDateTime

    .PARAMETER Limit
    The maximum number of AppleCare coverage records to return per request. Valid range is 1-1000. Only applies when All is not specified. Default behavior uses API's page size.

    .PARAMETER All
    When specified, retrieves all AppleCare coverage records by automatically handling pagination.

    .PARAMETER Raw
    When specified, returns the complete API response object including metadata and pagination links. Otherwise returns only the coverage data array.

    .OUTPUTS
    System.Object
    When Raw is not specified: Returns array of PSCustomObject with AppleCare coverage information.
    When Raw is specified: Returns the full API response object with pagination metadata.

    .EXAMPLE
    Get-DeviceAppleCare -DeviceId 'ABC123DEF456'
    Gets all AppleCare coverage information for a specific device.

    .EXAMPLE
    Get-DeviceAppleCare -DeviceId 'ABC123DEF456' -Limit 50
    Gets the first 50 AppleCare coverage records for a device.

    .EXAMPLE
    Get-DeviceAppleCare -DeviceId 'ABC123DEF456' -All
    Gets all AppleCare coverage records, automatically handling pagination.

    .EXAMPLE
    Get-DeviceAppleCare -DeviceId 'ABC123DEF456' -Fields status, agreementNumber, startDateTime
    Gets specific AppleCare coverage fields for a device.

    .EXAMPLE
    Get-DeviceAppleCare -DeviceId 'ABC123DEF456' -All -Raw
    Gets all AppleCare coverage records and returns the complete API response with pagination metadata.

    .NOTES
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    https://developer.apple.com/documentation/applebusinessmanagerapi/get-all-apple-care-coverage-for-an-orgdevice
    #>
}