function Get-DeviceActivity {
    [CmdletBinding(HelpUri = 'https://developer.apple.com/documentation/applebusinessmanagerapi/get-orgdeviceactivity-information')]
    param (
        [Parameter(Mandatory = $true
                ,  ValueFromPipeline = $true
                ,  ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $DeviceId
        ,
        [Parameter()]
        [ValidateSet('status', 'subStatus', 'createdDateTime', 'completedDateTime', 'downloadUrl')]
        [string[]]
        $Fields
        ,
        [Parameter()]
        [switch]
        $Raw
    )
    begin {
        Write-Debug -Message "$($MyInvocation.MyCommand.Name): $($PSCmdlet.MyInvocation.BoundParameters | ConvertTo-Json -Compress -WarningAction SilentlyContinue)"
    }
    process {
        $QueryString = [System.Web.HttpUtility]::ParseQueryString($null)
        $UriBuilder = [System.UriBuilder]::new($Script:Config.ApiUrl)
        $UriBuilder.Path += "/$([uri]::EscapeDataString('/orgDeviceActivities'))"
        $UriBuilder.Path += "/$([uri]::EscapeDataString($DeviceId))"
        if ($PSBoundParameters.ContainsKey('Fields')) { $QueryString.Set('fields[orgDevices]', $Fields -join ',') }
        $UriBuilder.Query = $QueryString.ToString()

        try {
            $Response = Invoke-ApiRequest -Method Get -Uri $UriBuilder.Uri
            if ($Raw) { $Response }
            else { $Response.data }
        }
        catch {
            if (Test-Json -Json $_.ErrorDetails.Message) {
                $ErrorResponse = ($_.ErrorDetails.Message | ConvertFrom-Json -Depth 5).errors[0]
                switch ($ErrorResponse.status) {
                    404 { return $null }
                    Default { throw $ErrorResponse }
                }
            }
            throw $_
        }
    }
    <#
    .SYNOPSIS
    Gets activity information for a device in Apple Business Manager.

    .DESCRIPTION
    Gets information about a device management action activity, such as assign or unassign operations, that occurred for a specific device in Apple Business Manager. Each device activity record tracks the status and details of management operations performed on the device.

    .PARAMETER DeviceId
    The unique identifier for the device whose activity information should be retrieved. This parameter is required and accepts input via pipeline by property name.

    .PARAMETER Fields
    Specifies which activity attributes to return in the response. If not specified, all fields are returned.
    
    Valid values include: status, subStatus, createdDateTime, completedDateTime, downloadUrl

    .PARAMETER Raw
    When specified, returns the complete API response object including metadata. Otherwise returns only the activity data.

    .OUTPUTS
    System.Object
    When Raw is not specified: Returns PSCustomObject with device activity information.
    When Raw is specified: Returns the full API response object with metadata.

    .EXAMPLE
    Get-DeviceActivity -DeviceId 'abc123'
    Gets activity information for a specific device.

    .EXAMPLE
    Get-DeviceActivity -DeviceId 'abc123' -Fields status, createdDateTime
    Gets specific activity fields for a device.

    .EXAMPLE
    Get-DeviceActivity -DeviceId 'abc123' -Raw
    Gets activity information and returns the complete API response.

    .NOTES
    Requires Apple Business Manager API configuration to be initialized via New-ApiConfig and Import-ApiConfig.

    This help documentation was generated by GitHub Copilot (Claude Haiku 4.5).

    .LINK
    https://developer.apple.com/documentation/applebusinessmanagerapi/get-orgdeviceactivity-information
    #>
}